### ISSUE TITLE
Rewrite Modules

### ISSUE THREAD

**Issue by AlexDev404** [Trail-Blaze/dyna-core-beta#2]
Rewrite:

- [x] `oauth.js` 
- [x] `mcp.js` 
- [x] `api.js`

**Comment by AlexDev404** [comment]
@Sparmage Yes, please start on one.

**Comment by AlexDev404** [comment]
@Sparmage @VinzyYT Looks like I had to do everything by myself again

**Comment by Sparmage** [comment]
@AlexDev404 sorry I've been doing stuff lately
